stages:
  - build
  - test
  - checkstyle
  - deploy

build:
  stage: build
  image: maven:3.3.9-jdk-8
  script:
    - mvn clean package

test:
    stage: test
    image: maven:3.3.9-jdk-8
    script:
    - echo "Test DEMO app"
    - mvn test && mvn jacoco:report
    - cat target/site/jacoco/index.html | grep -o '.*'
    coverage: "/Total.*?([0-9]{1,3})%/"

checkstyle:
    stage: checkstyle
    image: maven:3.3.9-jdk-8
    script:
    - echo "Checkstyle DEMO app"
    - mvn checkstyle:check
    
variables:
    APP_NAME: spring-project-ks2020
    DB_IP: ec2-18-203-62-227.eu-west-1.compute.amazonaws.com
    DB_PORT: 5432
    DB_USER: oodhfmjsniuhhk
    DB_PASSWORD: 1577539ea06e91c457749ddd706bbbc340f2d41ad846ffaa1b698faf0120e2af
    DB_DBNAME: d22jv6pimlu9vb
    
deploy:
  stage: deploy
  image: ruby:2.4
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=spring-project-ks2020 --api-key=$HEROKU_API_KEY
  only:
    - production